#!/bin/bash
#
# Swap which generated voice the app speaks with.
#
#   tools/use_voice.sh af_sarah     # then rebuild
#   tools/use_voice.sh              # list the voices available
#
# Voice sets live in VoiceClips/<voice>/ which is NOT part of the app target,
# so nothing there ships. This copies one set into ToddlerLearningApp/Resources/
# Speech/, which Xcode's synchronized group picks up automatically -- meaning a
# voice swap needs no project-file edit and no code change, just a rebuild.
#
# The clips are generated by gen_clips.py with Kokoro (Apache-2.0) on the dev
# Mac. See docs/VOICE_CLIPS.md.
#
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_root="$repo_root/VoiceClips"
target_dir="$repo_root/ToddlerLearningApp/Resources/Speech"

if [ ! -d "$source_root" ]; then
    echo "No VoiceClips/ directory — generate the clips first (see docs/VOICE_CLIPS.md)." >&2
    exit 1
fi

available=$(find "$source_root" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

if [ $# -eq 0 ]; then
    echo "Voices available:"
    echo "$available" | sed 's/^/  /'
    if [ -f "$target_dir/.voice" ]; then
        echo "In the app right now: $(cat "$target_dir/.voice")"
    else
        echo "In the app right now: none"
    fi
    exit 0
fi

voice="$1"
source_dir="$source_root/$voice"

if [ ! -d "$source_dir" ]; then
    echo "Unknown voice '$voice'. Available:" >&2
    echo "$available" | sed 's/^/  /' >&2
    exit 1
fi

count=$(find "$source_dir" -name '*.m4a' | wc -l | tr -d ' ')
if [ "$count" -eq 0 ]; then
    echo "No .m4a clips in $source_dir" >&2
    exit 1
fi

# Replaced wholesale rather than merged: a leftover clip from another voice
# would switch voices mid-lesson, which is exactly what RecordedSpeechService's
# per-sequence fallback exists to prevent.
rm -rf "$target_dir"
mkdir -p "$target_dir"
cp "$source_dir"/*.m4a "$target_dir/"
# Learn Numbers' counting timings (tools/gen_count_timings.py). Measured per
# voice, so they travel with that voice's clips.
if compgen -G "$source_dir/*.json" > /dev/null; then
    cp "$source_dir"/*.json "$target_dir/"
fi
echo "$voice" > "$target_dir/.voice"

echo "Now using $voice ($count clips). Rebuild to hear it."
